#!/bin/csh -f
set loc=`dirname $0`
set nam=`echo $HOST | cut -c1-4`
cd $loc
switch ($HOSTTYPE)
case 'x86_64-linux':
 ./vsim-ubuntu $*
 breaksw
case 'aarch64-linux':
 if ( $nam == 'cadp' ) then
 ./vsim-fugaku $*
 else
 ./vsim-acap $*
 endif
 breaksw
endsw
